### ISSUE TITLE
The parser stops when it encounters a NULL column definition

### ISSUE THREAD

**Issue by sanimesa** [shinichi-takii/ddlparse#68]
The below SQL produces only one column as output. 

**Input:**

```sql
CREATE TABLE sales (
	sale_id int4 NULL,
	posted_time timestamp,
	sale_hdr_title varchar,
	sale_inserted_at timestamp,
	sale_updated_at timestamp,
	sale_title varchar,
	sale_name varchar,
	sale_description text,
	sale_status varchar,
);
```

**Output:**

```sql
#standardSQL
CREATE TABLE `project.dataset.sales`
(
  sale_id INT64
)
```

**Comment by waltervos** [comment]
I can confirm this issue is bugging me as well. Modifying the "basic" testcase to include a NULL column throws an exception later down the line:

   File "c:\git\ddlparse\test\test_ddlparse.py", line 1263, in test_parse
    assert table.columns.to_bigquery_fields() == "[{}]".format(",".join(data["bq_field"]))

I'm still trying to get my head around pyparsing, but it seems the issue is related to this line (648):
```
Optional(Regex(r"\b(?:NOT\s+)NULL?\b", re.IGNORECASE))("null")
```

This appears to only match NOT NULL, and not NULL :)
